name: Deploy to GitHub Pages
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install material-design-icons-iconfont
        run: npm install material-design-icons-iconfont
      - name: Install dependencies
        run: npm ci && npm install material-design-icons-iconfont
      - name: Build project
        run: npm run build
      - name: Add external module
        run: |
          echo 'export default { build: { rollupOptions: { external: ["src/assets/watches/model2.png"] } } }' > vite.config.js  
          git add vite.config.js  
          git commit -m "Add external module" || true # Ignore error if there are no changes  
          git push
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist